### ISSUE TITLE
0.4.0 release

### ISSUE THREAD

**Issue by sosthene-nitrokey** [trussed-dev/heapless-bytes#4]
Updating to the latest `heapless` release is a breaking change, it might be an occasion to add other breaking changes to a 0.4.0 release.

- Remove the `remove` method: It is already implemented through `Deref` in heapless (though in a panicking way), and is unused as far as I know.
- Remove the `cbor` feature. In can very easily be implemented outside of the crate and is unlikely to be used since the Bytes struct is meant to be used within a struct.
- Remove the `from` function. It conflicts with the `From` trait.

Ideally I would even go to the point of removing the `Deref` trait impl and directly re-implementing all the heapless functions on top of it. This would make the documentation clearer. It would still be possible to implement `From`/`Into` a heapless Vec. This would make it possible to deref directly to a `[u8]`.

**Comment by robin-nitrokey** [comment]
I think this has been solved by https://github.com/trussed-dev/heapless-bytes/pull/8 and is included in [v0.4.0](https://github.com/trussed-dev/heapless-bytes/releases/tag/0.4.0)
